language: scala
scala: 2.12.6
jdk: oraclejdk8

cache:
  directories:
    - \$HOME/.ivy2/cache
    - \$HOME/.sbt
    - \$HOME/.coursier/cache

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: ...
    # GITHUB_TOKEN
    - secure: ...
    # GITHUB_ACCESS_TOKEN
    - secure: ...
    # DISCORD_WEBHOOK_TOKENS
    - secure: ...

install:
  - gem install octokit

  - git config --global user.email "bot@slamdata.com"
  - git config --global user.name "SlamData Bot"

script:
    - set -e

    - \$SBT ++\$TRAVIS_SCALA_VERSION test

    - |-
      if [ \$TRAVIS_PULL_REQUEST == "false" ] && [[ "\$TRAVIS_BRANCH" =~ backport/v.*|master ]]; then
        \$SBT transferPublishAndTagResources;
        TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/$name;format="lower,hyphen"$';
      fi

after_success:
  - |
    if [ \$TRAVIS_PULL_REQUEST != "false" ] && [[ \$TRAVIS_PULL_REQUEST_BRANCH =~ 'version-bump' ]]; then
      if [[ "\$(git diff HEAD^ | grep -e '^[-+][0-9]' | sed 's/^[+\-]//' | sed 's/\\.[0-9]*\$//' | uniq | wc -l)" -eq 2 ]]; then
        clone_dir=\$(mktemp -d "/tmp/slamdata-bump.XXXXXXXX")
        git clone --depth 1 https://\$GITHUB_TOKEN@github.com/slamdata/devtools.git \$clone_dir

        for t in "\$(scripts/listLabels | grep 'version: revision')"; do
          \$clone_dir/bin/sdmerge \$TRAVIS_REPO_SLUG \$TRAVIS_PULL_REQUEST
        done
      fi
    fi

  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/\$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/\$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*\$/

before_cache:
  - find "\$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
  - find "\$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
