name: build

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  GITHUB_ACTOR: precog-bot
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up JDK ${{ env.JDK }}
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Apply template
        run: src/main/g8/sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M g8
      - name: Test template
        run: |
          set -e
          cd target/g8
          ../../src/main/g8/sbt test

